set backspace=2         " backspace in insert mode works like normal editor
set colorcolumn=80      " highlight column at 80 chars
set hidden              " send unsaved buffers to the background without error
set mouse=              " disable mouse
set nobackup            " get rid of anoying ~file
set nocompatible        " disable old-vi compatibility mode
set nohlsearch          " disable search highlighting
set number              " line numbers
set showmatch           " highlight matching bracket

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

" Plugins from Github
Plugin 'Quramy/tsuquyomi'
Plugin 'Shougo/vimproc.vim'
Plugin 'altercation/vim-colors-solarized.git'
Plugin 'alvaromorales/pyflakes-vim'
Plugin 'cakebaker/scss-syntax.vim'
Plugin 'ervandew/supertab'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }
Plugin 'junegunn/fzf.vim'
Plugin 'leafgarland/typescript-vim'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'pangloss/vim-javascript'
Plugin 'scrooloose/nerdtree'
Plugin 'tell-k/vim-autopep8'
Plugin 'tpope/vim-git'
Plugin 'tpope/vim-surround'
Plugin 'vim-ruby/vim-ruby'
Plugin 'vim-scripts/matchit.zip'
Plugin 'vim-scripts/pep8'

call vundle#end()

" Global settings for all files (but may be overridden in ftplugin).
setlocal tabstop=4
setlocal softtabstop=4
setlocal shiftwidth=4
setlocal smarttab
setlocal expandtab

" Syntax highlighting
syntax on                    " syntax highlighing
filetype on                  " try to detect filetypes
filetype plugin indent on    " enable loading indent file for filetype

" Solarized
let g:solarized_termtrans = 1
set background=dark
colorscheme solarized

" NerdTree
map <F2> :NERDTreeToggle<CR>

" Code Folding
set foldmethod=indent
set foldlevel=99

" Window Movement
"   Vertical Split : Ctrl+w + v
"   Horizontal Split: Ctrl+w + s
"   Close current windows: Ctrl+w + q
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

" Quickfix window reference
" :copen " Open the quickfix window
" :ccl   " Close it
" :cw    " Open it if there are 'errors', close it otherwise (some people prefer this)
" :cn    " Go to the next error in the window
" :cnf   " Go to the first error in the next file

" Pyflakes
let g:pyflakes_use_quickfix = 0      " no quickfix window for pyflakes

" Pep8
let g:pep8_map='<F7>'

" Autopep8
let g:autopep8_ignore="E501"
let g:autopep8_disable_show_diff=1

" tsuquyomi
let g:tsuquyomi_disable_quickfix = 1

" Tab Completion and Doc
au FileType python set omnifunc=pythoncomplete#Complete
let g:SuperTabDefaultCompletionType = "context"
set completeopt=menuone,longest
" set completeopt-=preview

" fzf
map <leader>t :Files<CR>
map ; :Buffers<CR>

" Toggle line numbers
map <leader>n :set nu!<CR>

" Redraw
map <leader>r :redraw!<CR>

" Neovim-specific configuration
if has('nvim')
  tnoremap <Esc> <C-\><C-n>    " use Esc to enter normal mode in terminal
  nmap <BS> <C-W>h             " temp workaround, see neovim issue #2048
  let g:python_host_prog=$WORKON_HOME."/nvim/bin/python"
endif

" Common indent settings
map <leader>2 :setlocal expandtab shiftwidth=2 tabstop=2<CR>
map <leader>4 :setlocal expandtab shiftwidth=4 tabstop=4<CR>

" Indentation overrides
autocmd FileType html setlocal expandtab shiftwidth=2 tabstop=2
autocmd FileType javascript setlocal expandtab shiftwidth=2 tabstop=2
autocmd FileType ruby setlocal expandtab shiftwidth=2 tabstop=2
